export const producers = [
  {
    id: "andes-spirit",
    name: "Destileria Andes Spirit",
    region: "Valle del Elqui, Chile",
    address: "Camino Rural km 7, Vicuña",
    masterDistiller: "Maestra Destiladora: Carolina Rojas",
    description:
      "Pequena destileria de autor enfocada en piscos de alta gama, trabajando solo uvas del Valle del Elqui.",
    hasShop: true,
    hasTours: true,
    schedule: "Lunes a sabado, 10:00 - 18:00",
    images: [
      "Foto sala de barricas",
      "Foto alambique de cobre",
      "Foto terraza de degustacion",
    ],
  },
  {
    id: "patagonia-craft",
    name: "Patagonia Craft Distillery",
    region: "Puerto Varas, Chile",
    address: "Ruta 225, Km 3, Camino Ensenada",
    masterDistiller: "Master Distiller: Tomás Aguilar",
    description:
      "Destileria patagonica que combina botanicos locales con tecnicas modernas para crear gin y licores unicos.",
    hasShop: true,
    hasTours: false,
    schedule: "Jueves a domingo, 12:00 - 20:00",
    images: [
      "Foto vista al lago",
      "Foto sala de destilacion",
      "Foto barra de cata",
    ],
  },
];

export const products = [
  {
    id: "pisco-origen-andino",
    producerId: "andes-spirit",
    name: "Pisco Origen Andino",
    type: "Pisco",
    abv: 40,
    volume: 750,
    country: "Chile",
    rating: 4.3,
    notesCount: 58,
    price: 16500,
    stock: true,
    medals: ["Oro Catad'Or 2023"],
    flavorProfile: ["frutal", "citricos", "floral"],
    shortDescription:
      "Pisco transparente, muy aromatico, ideal para sour clasico y cocteles frescos.",
  },
  {
    id: "pisco-guardado-cobre",
    producerId: "andes-spirit",
    name: "Pisco Guardado en Cobre",
    type: "Pisco",
    abv: 42,
    volume: 700,
    country: "Chile",
    rating: 4.6,
    notesCount: 73,
    price: 18500,
    stock: true,
    medals: ["Doble oro Spirits Selection 2022"],
    flavorProfile: ["frutal maduro", "especiado", "madera suave"],
    shortDescription:
      "Pisco reposado de color ambar suave, con notas de madera y especias dulces.",
  },
  {
    id: "gin-bosque-sur",
    producerId: "patagonia-craft",
    name: "Gin Bosque del Sur",
    type: "Gin",
    abv: 43,
    volume: 700,
    country: "Chile",
    rating: 4.5,
    notesCount: 64,
    price: 19900,
    stock: true,
    medals: ["Plata World Gin Awards 2024"],
    flavorProfile: ["enebro", "herbal", "citricos"],
    shortDescription:
      "Gin patagonico con enebro, murtilla y cascara de limon; perfecto para gin tonic aromaticos.",
  },
  {
    id: "licor-frutos-patagonia",
    producerId: "patagonia-craft",
    name: "Licor Frutos de la Patagonia",
    type: "Licor",
    abv: 28,
    volume: 500,
    country: "Chile",
    rating: 4.1,
    notesCount: 39,
    price: 12900,
    stock: false,
    medals: [],
    flavorProfile: ["frutos rojos", "dulce", "suave"],
    shortDescription:
      "Licor dulce a base de frutos rojos patagonicos, ideal para cocteles de baja gradacion.",
  },
];

export const cocktails = [
  {
    id: "sour-andino-fresco",
    name: "Sour Andino Fresco",
    mainProductId: "pisco-origen-andino",
    mainSpiritType: "Pisco",
    intensity: "suave",
    mixologist: "Carolina Rojas",
    ingredients: [
      "60 ml Pisco Origen Andino",
      "30 ml jugo de limon fresco",
      "20 ml syrup simple",
      "Hielo",
      "Gotas de amargo de angostura",
    ],
    preparation:
      "Agregar todos los ingredientes (menos el amargo) a una coctelera con hielo, agitar enérgicamente y colar en copa fria. Terminar con 2 o 3 gotas de amargo sobre la espuma.",
  },
  {
    id: "sour-cobre-especiado",
    name: "Sour Cobre Especiado",
    mainProductId: "pisco-guardado-cobre",
    mainSpiritType: "Pisco",
    intensity: "medio",
    mixologist: "Invitado DALMA",
    ingredients: [
      "60 ml Pisco Guardado en Cobre",
      "25 ml jugo de limon",
      "20 ml syrup de miel",
      "1 clara de huevo (opcional)",
      "Hielo",
      "Ralladura de naranja",
    ],
    preparation:
      "Agitar todos los ingredientes sin hielo (dry shake), luego agregar hielo y volver a agitar. Servir en copa y decorar con ralladura de naranja.",
  },
  {
    id: "gin-tonic-bosque",
    name: "Gin Tonic Bosque del Sur",
    mainProductId: "gin-bosque-sur",
    mainSpiritType: "Gin",
    intensity: "medio",
    mixologist: "Tomás Aguilar",
    ingredients: [
      "50 ml Gin Bosque del Sur",
      "Agua tonica bien fria",
      "Rodaja de limon",
      "Ramita de romero",
      "Hielo en cubos",
    ],
    preparation:
      "Llenar un vaso alto con hielo, agregar el gin y completar con tonica al gusto. Decorar con limon y romero.",
  },
  {
    id: "spritz-frutos-patagonia",
    name: "Spritz Frutos de la Patagonia",
    mainProductId: "licor-frutos-patagonia",
    mainSpiritType: "Licor",
    intensity: "suave",
    mixologist: "Invitado DALMA",
    ingredients: [
      "60 ml Licor Frutos de la Patagonia",
      "60 ml espumante brut bien frio",
      "30 ml soda",
      "Rodaja de naranja",
      "Hielo",
    ],
    preparation:
      "En copa con hielo agregar el licor, luego el espumante y terminar con un toque de soda. Mezclar suavemente y decorar con naranja.",
  },
];
